function PolUpdatePlot

global polUpdatePlotFig
global polPlotParameters

polUpdatePlotFig = figure('units','normalized','outerposition',[.3 .3 .4 .4],'menubar','none',...
    'numbertitle','off','name','Polarization display parameters');

% Axes type
uicontrol('style','text','units','normalized','position',[.01 .9 .23 .08],...
    'string','Axes type','horizontalalignment','left','fontunits','normalized','fontsize',.5,...
    'backgroundcolor',[.7 .7 .7])
temp = find(strcmpi(polPlotParameters.axesType,{'Cartesian','Polar'}));
uicontrol('style','popupmenu','units','normalized','position',[.24 .9 .23 .08],'tag','axes_type',...
    'string',{'Cartesian','Polar'},'value',temp,'horizontalalignment','right','fontunits','normalized','fontsize',.5)
% Frequency axis type
uicontrol('style','text','units','normalized','position',[.01 .81 .23 .08],...
    'string','Freq Axis','horizontalalignment','left','fontunits','normalized','fontsize',.5,...
    'backgroundcolor',[.7 .7 .7])
temp = find(strcmpi(polPlotParameters.freqAxis,{'Linear','Logarithmic'}));
uicontrol('style','popupmenu','units','normalized','position',[.24 .81 .23 .08],'tag','frequency_axis',...
    'string',{'Linear','Logarithmic'},'value',temp,'horizontalalignment','right','fontunits','normalized','fontsize',.5)
% Frequency limits
uicontrol('style','text','units','normalized','position',[.01 .72 .23 .08],...
    'string','Freq Limits [Hz]','horizontalalignment','left','fontunits','normalized','fontsize',.5,...
    'backgroundcolor',[.7 .7 .7])
uicontrol('style','edit','units','normalized','position',[.24 .72 .23 .08],'tag','frequency_limits',...
    'string',[num2str(polPlotParameters.freqLim(1)) '-' num2str(polPlotParameters.freqLim(2))],'horizontalalignment','right','fontunits','normalized','fontsize',.5,...
    'tooltipstring',['Indicate F1-F2' 10,...
    'The lower limit should be 1/(time window/10)' 10,...
    '''auto'' option: range spans from 1/(time window/10) to Fny'])
% Colormap
uicontrol('style','text','units','normalized','position',[.01 .63 .23 .08],...
    'string','Colormap','horizontalalignment','left','fontunits','normalized','fontsize',.5,...
    'backgroundcolor',[.7 .7 .7])
temp = find(strcmpi(polPlotParameters.colormap,{'parula','jet','cmapwbr','hsv','hot','cool','spring','summer','autumn','winter','gray','bone','copper','pink'}));
uicontrol('style','popupmenu','units','normalized','position',[.24 .63 .23 .08],'tag','colormap_name',...
    'string',{'parula','jet','cmapwbr','hsv','hot','cool','spring','summer','autumn','winter','gray','bone','copper','pink'},'value',temp,...
    'horizontalalignment','right','fontunits','normalized','fontsize',.5)
% Colormap range
uicontrol('style','text','units','normalized','position',[.01 .54 .23 .08],...
    'string','Colormap range','horizontalalignment','left','fontunits','normalized','fontsize',.5,...
    'backgroundcolor',[.7 .7 .7])
uicontrol('style','edit','units','normalized','position',[.24 .54 .23 .08],'tag','colormap_range',...
    'string',polPlotParameters.colormapRange,'horizontalalignment','right','fontunits','normalized','fontsize',.5,...
    'tooltipstring',['Indicate Cmin-Cmax' 10 '''auto'' option: range spans from min(data) to max(data)'])

% H/HVSR Angular Rule
uicontrol('style','text','units','normalized','position',[.01 .42 .23 .08],...
    'string','H/HVSR angular rule','horizontalalignment','left','fontunits','normalized','fontsize',.5,...
    'backgroundcolor',[.7 .7 .7])
temp = find(strcmpi(polPlotParameters.HVSRAngularRule,{'0° = N, increasing clockwise','0° = E, increasing counterclockwise'}));
uicontrol('style','popupmenu','units','normalized','position',[.24 .42 .23 .08],'tag','HVSR_angular_rule',...
    'string',{'0° = N, increasing clockwise','0° = E, increasing counterclockwise'},'value',temp,'horizontalalignment','right','fontunits','normalized','fontsize',.5)

% SVD ThetaH Rule
uicontrol('style','text','units','normalized','position',[.01 .3 .23 .08],...
    'string','SVD ThetaH rule','horizontalalignment','left','fontunits','normalized','fontsize',.5,...
    'backgroundcolor',[.7 .7 .7])
temp = find(strcmpi(polPlotParameters.SVDThetaHRule,{'0° = N, increasing clockwise','0° = E, increasing counterclockwise'}));
uicontrol('style','popupmenu','units','normalized','position',[.24 .3 .23 .08],'tag','SVD_thetaH_rule',...
    'string',{'0° = N, increasing clockwise','0° = E, increasing counterclockwise'},'value',temp,'horizontalalignment','right','fontunits','normalized','fontsize',.5)
% SVD ThetaV Rule
uicontrol('style','text','units','normalized','position',[.01 .21 .23 .08],...
    'string','SVD ThetaV rule','horizontalalignment','left','fontunits','normalized','fontsize',.5,...
    'backgroundcolor',[.7 .7 .7])
temp = find(strcmpi(polPlotParameters.SVDThetaVRule,{'0° = Horizontal','0° = Vertical'}));
uicontrol('style','popupmenu','units','normalized','position',[.24 .21 .23 .08],'tag','SVD_thetaV_rule',...
    'string',{'0° = Horizontal','0° = Vertical'},'value',temp,'horizontalalignment','right','fontunits','normalized','fontsize',.5)

%% PUSHBUTTONS ------------------------------------------------------------
% Update
uicontrol('style','pushbutton','units','normalized','position',[.7 .01 .1 .08],...
    'string','Update','horizontalalignment','left','fontunits','normalized','fontsize',.5,...
    'backgroundcolor',[.7 .7 .7],'callback','PolUpdatePlotParameters(data_processing(1).fs)')
% Cancel
uicontrol('style','pushbutton','units','normalized','position',[.85 .01 .1 .08],...
    'string','Cancel','horizontalalignment','left','fontunits','normalized','fontsize',.5,...
    'backgroundcolor',[.7 .7 .7],'callback','delete(gcf);')

end



